# Keycloak
keycloak:
  realm: keycloak-realm
  baseUrl: http://localhost:8098
  client-secret: FtqtoZc6TaA7dq5MeXTBFu3GQcsQJ7cz
  client-id: keycloak-clientId
  grant-type: password
  name: momojoop
  password: passer@1
  tokenUrl: http://localhost:8098/realms/keycloak-realm/protocol/openid-connect/token
  introspection-uri: http://localhost:8098/realms/keycloak-realm/protocol/openid-connect/token/introspect

jwt:
  jwk-set-uri: http://localhost:8098/realms/keycloak-realm/protocol/openid-connect/certs
  token:
    converter:
      principal-attribute: preferred_username

# App config
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8098/realms/keycloak-realm
  messages:
    basename: classpath:messages

  # Configuration du DataSource
  application:
    name: keycloak-app

server:
  port: 8000